services:
  # 1. Database 서비스 (MySQL)
  service-board-mysql:
    image: soyoung0/mysql:board-proxy  # 태그 통일
    container_name: mysql-primary-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "ian1234!"
      MYSQL_DATABASE: "st7db"
      MYSQL_USER: "dev"                # FastAPI와 맞추기 위해 dev로 수정 권장
      MYSQL_PASSWORD: "dev1234!"       # FastAPI와 맞추기 위해 dev1234!로 수정 권장
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    networks:
      - board-network

  # 2. Application 서비스 (FastAPI)
  service-board-fastapi:
    image: soyoung0/fastapi:board-proxy
    container_name: board-fastapi-container
    restart: always
    depends_on:
      - service-board-mysql
    environment:
      DB_HOST: "mysql-primary-container"
      DB_USER: "dev"
      DB_PASSWORD: "dev1234!"
      DB_NAME: "st7db"
    ports:
      - "8000:8000"
    networks:
      - board-network

  # 3. Web 서비스 (Nginx)
  service-board-nginx:
    image: soyoung0/nginx:board-proxy
    container_name: board-nginx-container
    restart: always
    depends_on:
      - service-board-fastapi
    ports:
      - "80:80"
    networks:
      - board-network

networks:
  board-network:
    driver: bridge