services:
  service-board-nginx:
    image: soyoung0/nginx:board-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
      platforms: ["linux/amd64", "linux/arm64"]
    container_name: board-nginx-container
    restart: always
    depends_on:
      - service-board-fastapi
    ports:
      - "80:80"
    networks:
      - board-network

networks:
  board-network:
    driver: bridge
